----------------------------------
--     AUTOGENERATED FILE       --
-- File generated with glossgen --
----------------------------------

-- Internal glossary for enumeration, lookups, constants and so on.
local Glossary = {
    rootPath = "plugins.cyber_engine_tweaks.mods.bartmoss."
}

Glossary.Cyberware = { 
	Skeleton = { 
		Legendary = {
			Microrotors = "Items.CyberRotorsLegendary",
			Synaptic Singal Optimizer = "Items.EndoskeletonLegendary",
			Bionic Lungs = "Items.EnhancedTissueLegendary"
		},
		Epic = {
			Microrotors = "Items.CyberRotorsLegendary",
			Synaptic Singal Optimizer = "Items.EndoskeletonLegendary",
			Bionic Lungs = "Items.EnhancedTissueLegendary"
		},
		Rare = {
			Microrotors = "Items.CyberRotorsLegendary",
			Synaptic Singal Optimizer = "Items.EndoskeletonLegendary",
			Bionic Lungs = "Items.EnhancedTissueLegendary"
		},
		Uncommon = {
			Microrotors = "Items.CyberRotorsLegendary",
			Synaptic Singal Optimizer = "Items.EndoskeletonLegendary",
			Bionic Lungs = "Items.EnhancedTissueLegendary"
		},
		Common = {
			Microrotors = "Items.CyberRotorsLegendary",
			Synaptic Singal Optimizer = "Items.EndoskeletonLegendary",
			Bionic Lungs = "Items.EnhancedTissueLegendary"
		},
	}
}
